### ISSUE TITLE
The training graphic-card in the paper is a 4090 (24GB) but I'm OOM with another A6000 Ada (48GB)

### ISSUE THREAD

**Issue by Fan-QY** [Howard-coder191/Relation3D#4]
The results of your work are very empirical, but I'm now having problems reproducing it that I can't reproduce with the larger graphics card.

Is there something wrong?

```
Singularity> CUDA_VISIBLE_DEVICES=1 python3 tools/train.py configs/scannet/relation3d_scannet.yaml 
2025-08-15 11:47:46,261 - INFO - config: configs/scannet/relation3d_scannet.yaml
2025-08-15 11:47:46,279 - INFO - set random seed: 1999
2025-08-15 11:47:46,304 - INFO - Config (path: configs/scannet/relation3d_scannet.yaml)
{
    "train": {
        "seed": 1999,
        "epochs": 512,
        "interval": 16,
        "pretrain": "checkpoints/sstnet_pretrain.pth"
    },
    "test": {
        "seed": 1999,
        "test_topk_per_scene": 100,
        "test_score_thresh": 0.0,
        "test_npoint_thresh": 100
    },
    "dataloader": {
        "train": {
            "batch_size": 6,
            "num_workers": 8,
            "persistent_workers": true
        },
        "val": {
            "batch_size": 1,
            "num_workers": 4,
            "persistent_workers": true
        },
        "test": {
            "batch_size": 1,
            "num_workers": 4,
            "persistent_workers": true
        }
    },
    "data": {
        "train": {
            "type": "scannetv2",
            "data_root": "./datasets/scannetv2",
            "prefix": "train",
            "suffix": "_inst_nostuff.pth",
            "training": true,
            "mode": 4,
            "with_elastic": true,
            "use_xyz": true,
            "voxel_cfg": {
                "scale": 50,
                "spatial_shape": [
                    128,
                    512
                ],
                "max_npoint": 250000
            }
        },
        "val": {
            "type": "scannetv2",
            "data_root": "./datasets/scannetv2",
            "prefix": "val",
            "suffix": "_inst_nostuff.pth",
            "training": false,
            "mode": 4,
            "with_elastic": false,
            "use_xyz": true,
            "voxel_cfg": {
                "scale": 50,
                "spatial_shape": [
                    128,
                    512
                ],
                "max_npoint": 250000
            }
        },
        "test": {
            "type": "scannetv2",
            "data_root": "./datasets/scannetv2",
            "prefix": "val",
            "suffix": "_inst_nostuff.pth",
            "training": false,
            "mode": 4,
            "with_elastic": false,
            "use_xyz": true,
            "voxel_cfg": {
                "scale": 50,
                "spatial_shape": [
                    128,
                    512
                ],
                "max_npoint": 250000
            }
        }
    },
    "model": {
        "name": "Relation3D",
        "input_channel": 9,
        "blocks": 5,
        "block_reps": 2,
        "media": 32,
        "normalize_before": true,
        "return_blocks": true,
        "pool": "max",
        "num_class": 18,
        "decoder": {
            "num_layer": 6,
            "num_query": 400,
            "d_model": 256,
            "nhead": 8,
            "hidden_dim": 1024,
            "dropout": 0.0,
            "activation_fn": "gelu",
            "iter_pred": true,
            "attn_mask": true,
            "pe": false,
            "temperature": 10000,
            "pos_type": "fourier",
            "attn_mask_thresh": 0.1,
            "quant_grid_length": 24,
            "grid_size": 0.1,
            "rel_query": true,
            "rel_key": true,
            "rel_value": true
        },
        "criterion": {
            "loss_weight": [
                0.5,
                1.0,
                1.0,
                0.5,
                0.5
            ],
            "cost_weight": [
                0.5,
                1.0,
                1.0,
                0.5
            ],
            "non_object_weight": 0.1
        },
        "test_cfg": {
            "topk_insts": 800,
            "score_thr": 0.0,
            "npoint_thr": 100
        },
        "norm_eval": false,
        "fix_module": []
    },
    "optimizer": {
        "type": "AdamW",
        "lr": 0.0002,
        "weight_decay": 0.05
    },
    "lr_scheduler": {
        "type": "PolyLR",
        "max_iters": 512,
        "power": 0.9,
        "constant_ending": 0.0
    },
    "work_dir": "./exps/relation3d_scannet"
}
/opt/conda/lib/python3.10/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
2025-08-15 11:47:59,455 - INFO - Relation3D(
  (input_conv): SparseSequential(
    (0): SubMConv3d(9, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
  )
  (unet): UBlock(
    (blocks): SparseSequential(
      (block0): ResidualBlock(
        (i_branch): SparseSequential(
          (0): Identity()
        )
        (conv_branch): SparseSequential(
          (0): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          (3): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (4): ReLU()
          (5): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
      )
      (block1): ResidualBlock(
        (i_branch): SparseSequential(
          (0): Identity()
        )
        (conv_branch): SparseSequential(
          (0): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          (3): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (4): ReLU()
          (5): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
      )
    )
    (conv): SparseSequential(
      (0): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
      (1): ReLU()
      (2): SparseConv3d(32, 64, kernel_size=[2, 2, 2], stride=[2, 2, 2], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
    )
    (u): UBlock(
      (blocks): SparseSequential(
        (block0): ResidualBlock(
          (i_branch): SparseSequential(
            (0): Identity()
          )
          (conv_branch): SparseSequential(
            (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            (3): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (4): ReLU()
            (5): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
        )
        (block1): ResidualBlock(
          (i_branch): SparseSequential(
            (0): Identity()
          )
          (conv_branch): SparseSequential(
            (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            (3): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (4): ReLU()
            (5): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
        )
      )
      (conv): SparseSequential(
        (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
        (1): ReLU()
        (2): SparseConv3d(64, 96, kernel_size=[2, 2, 2], stride=[2, 2, 2], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
      )
      (u): UBlock(
        (blocks): SparseSequential(
          (block0): ResidualBlock(
            (i_branch): SparseSequential(
              (0): Identity()
            )
            (conv_branch): SparseSequential(
              (0): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (1): ReLU()
              (2): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              (3): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (4): ReLU()
              (5): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            )
          )
          (block1): ResidualBlock(
            (i_branch): SparseSequential(
              (0): Identity()
            )
            (conv_branch): SparseSequential(
              (0): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (1): ReLU()
              (2): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              (3): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (4): ReLU()
              (5): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            )
          )
        )
        (conv): SparseSequential(
          (0): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SparseConv3d(96, 128, kernel_size=[2, 2, 2], stride=[2, 2, 2], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
        (u): UBlock(
          (blocks): SparseSequential(
            (block0): ResidualBlock(
              (i_branch): SparseSequential(
                (0): Identity()
              )
              (conv_branch): SparseSequential(
                (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (1): ReLU()
                (2): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                (3): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (4): ReLU()
                (5): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              )
            )
            (block1): ResidualBlock(
              (i_branch): SparseSequential(
                (0): Identity()
              )
              (conv_branch): SparseSequential(
                (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (1): ReLU()
                (2): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                (3): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (4): ReLU()
                (5): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              )
            )
          )
          (conv): SparseSequential(
            (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SparseConv3d(128, 160, kernel_size=[2, 2, 2], stride=[2, 2, 2], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
          (u): UBlock(
            (blocks): SparseSequential(
              (block0): ResidualBlock(
                (i_branch): SparseSequential(
                  (0): Identity()
                )
                (conv_branch): SparseSequential(
                  (0): BatchNorm1d(160, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                  (1): ReLU()
                  (2): SubMConv3d(160, 160, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                  (3): BatchNorm1d(160, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                  (4): ReLU()
                  (5): SubMConv3d(160, 160, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                )
              )
              (block1): ResidualBlock(
                (i_branch): SparseSequential(
                  (0): Identity()
                )
                (conv_branch): SparseSequential(
                  (0): BatchNorm1d(160, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                  (1): ReLU()
                  (2): SubMConv3d(160, 160, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                  (3): BatchNorm1d(160, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                  (4): ReLU()
                  (5): SubMConv3d(160, 160, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                )
              )
            )
          )
          (deconv): SparseSequential(
            (0): BatchNorm1d(160, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SparseInverseConv3d(160, 128, kernel_size=[2, 2, 2], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
          (blocks_tail): SparseSequential(
            (block0): ResidualBlock(
              (i_branch): SparseSequential(
                (0): SubMConv3d(256, 128, kernel_size=[1, 1, 1], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              )
              (conv_branch): SparseSequential(
                (0): BatchNorm1d(256, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (1): ReLU()
                (2): SubMConv3d(256, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                (3): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (4): ReLU()
                (5): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              )
            )
            (block1): ResidualBlock(
              (i_branch): SparseSequential(
                (0): Identity()
              )
              (conv_branch): SparseSequential(
                (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (1): ReLU()
                (2): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
                (3): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
                (4): ReLU()
                (5): SubMConv3d(128, 128, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              )
            )
          )
        )
        (deconv): SparseSequential(
          (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SparseInverseConv3d(128, 96, kernel_size=[2, 2, 2], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
        (blocks_tail): SparseSequential(
          (block0): ResidualBlock(
            (i_branch): SparseSequential(
              (0): SubMConv3d(192, 96, kernel_size=[1, 1, 1], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            )
            (conv_branch): SparseSequential(
              (0): BatchNorm1d(192, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (1): ReLU()
              (2): SubMConv3d(192, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              (3): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (4): ReLU()
              (5): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            )
          )
          (block1): ResidualBlock(
            (i_branch): SparseSequential(
              (0): Identity()
            )
            (conv_branch): SparseSequential(
              (0): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (1): ReLU()
              (2): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
              (3): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
              (4): ReLU()
              (5): SubMConv3d(96, 96, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            )
          )
        )
      )
      (deconv): SparseSequential(
        (0): BatchNorm1d(96, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
        (1): ReLU()
        (2): SparseInverseConv3d(96, 64, kernel_size=[2, 2, 2], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
      )
      (blocks_tail): SparseSequential(
        (block0): ResidualBlock(
          (i_branch): SparseSequential(
            (0): SubMConv3d(128, 64, kernel_size=[1, 1, 1], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
          (conv_branch): SparseSequential(
            (0): BatchNorm1d(128, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SubMConv3d(128, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            (3): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (4): ReLU()
            (5): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
        )
        (block1): ResidualBlock(
          (i_branch): SparseSequential(
            (0): Identity()
          )
          (conv_branch): SparseSequential(
            (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (1): ReLU()
            (2): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
            (3): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
            (4): ReLU()
            (5): SubMConv3d(64, 64, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          )
        )
      )
    )
    (deconv): SparseSequential(
      (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
      (1): ReLU()
      (2): SparseInverseConv3d(64, 32, kernel_size=[2, 2, 2], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
    )
    (blocks_tail): SparseSequential(
      (block0): ResidualBlock(
        (i_branch): SparseSequential(
          (0): SubMConv3d(64, 32, kernel_size=[1, 1, 1], stride=[1, 1, 1], padding=[0, 0, 0], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
        (conv_branch): SparseSequential(
          (0): BatchNorm1d(64, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SubMConv3d(64, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          (3): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (4): ReLU()
          (5): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
      )
      (block1): ResidualBlock(
        (i_branch): SparseSequential(
          (0): Identity()
        )
        (conv_branch): SparseSequential(
          (0): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (1): ReLU()
          (2): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
          (3): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
          (4): ReLU()
          (5): SubMConv3d(32, 32, kernel_size=[3, 3, 3], stride=[1, 1, 1], padding=[1, 1, 1], dilation=[1, 1, 1], output_padding=[0, 0, 0], bias=False, algo=ConvAlgo.MaskImplicitGemm)
        )
      )
    )
  )
  (output_layer): SparseSequential(
    (0): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (1): ReLU(inplace=True)
  )
  (mlp): Sequential(
    (0): Linear(in_features=64, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=32, bias=True)
  )
  (pooling_linear): MLP(
    (0): Linear(in_features=32, out_features=32, bias=True)
    (1): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=32, out_features=32, bias=True)
    (4): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=1, bias=True)
  )
  (pooling_linear1): MLP(
    (0): Linear(in_features=32, out_features=32, bias=True)
    (1): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=32, out_features=32, bias=True)
    (4): BatchNorm1d(32, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=1, bias=True)
  )
  (coords_linear): MLP(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): BatchNorm1d(3, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=3, out_features=3, bias=True)
    (4): BatchNorm1d(3, eps=0.0001, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=3, out_features=32, bias=True)
  )
  (decoder): QueryDecoder(
    (input_proj): Sequential(
      (0): Linear(in_features=32, out_features=256, bias=True)
      (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (2): ReLU()
    )
    (refpoint_embed): Embedding(400, 3)
    (key_position_embedding): PositionEmbeddingCoordsSine(type=fourier, scale=6.283185307179586, normalize=True, gaussB=torch.Size([3, 128]), gaussBsum=-10.104107856750488)
    (decoder): TransformerDecoder(
      (layers): ModuleList(
        (0): TransformerDecoderLayer(
          (sa_qcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_qpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_kcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_kpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_v_proj): Linear(in_features=256, out_features=256, bias=True)
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (ca_qcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_kcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_kpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_v_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_sine_proj): Linear(in_features=256, out_features=256, bias=True)
          (cross_attn): MultiheadAttentionRPE(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (linear1): Linear(in_features=256, out_features=1024, bias=True)
          (dropout): Dropout(p=0.0, inplace=False)
          (linear2): Linear(in_features=1024, out_features=256, bias=True)
          (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.0, inplace=False)
          (dropout2): Dropout(p=0.0, inplace=False)
          (dropout3): Dropout(p=0.0, inplace=False)
        )
        (1-5): 5 x TransformerDecoderLayer(
          (sa_qcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_qpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_kcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_kpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (sa_v_proj): Linear(in_features=256, out_features=256, bias=True)
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (ca_qcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_proj): None
          (ca_kcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_kpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_v_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_sine_proj): Linear(in_features=256, out_features=256, bias=True)
          (cross_attn): MultiheadAttentionRPE(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (linear1): Linear(in_features=256, out_features=1024, bias=True)
          (dropout): Dropout(p=0.0, inplace=False)
          (linear2): Linear(in_features=1024, out_features=256, bias=True)
          (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.0, inplace=False)
          (dropout2): Dropout(p=0.0, inplace=False)
          (dropout3): Dropout(p=0.0, inplace=False)
        )
      )
      (layers_cross): ModuleList(
        (0-1): 2 x TransformerDecoderCrossLayer(
          (ca_qcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_kcontent_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_kpos_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_v_proj): Linear(in_features=256, out_features=256, bias=True)
          (ca_qpos_sine_proj): Linear(in_features=256, out_features=256, bias=True)
          (cross_attn): MultiheadAttentionRPE(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
          )
          (linear1): Linear(in_features=256, out_features=1024, bias=True)
          (dropout): Dropout(p=0.0, inplace=False)
          (linear2): Linear(in_features=1024, out_features=256, bias=True)
          (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (norm3): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.0, inplace=False)
          (dropout2): Dropout(p=0.0, inplace=False)
          (dropout3): Dropout(p=0.0, inplace=False)
        )
      )
      (norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
      (position_embedding): PositionEmbeddingCoordsSine(type=fourier, scale=6.283185307179586, normalize=False, gaussB=torch.Size([3, 128]), gaussBsum=-15.020824432373047)
      (ref_point_head): MLP(
        (layers): ModuleList(
          (0-1): 2 x Linear(in_features=256, out_features=256, bias=True)
        )
      )
      (bbox_embed): MLP(
        (layers): ModuleList(
          (0-1): 2 x Linear(in_features=256, out_features=256, bias=True)
          (2): Linear(in_features=256, out_features=3, bias=True)
        )
      )
      (position_relation_embedding): PositionRelationEmbedding(
        (pos_proj): Conv2dNormActivation(
          (0): Conv2d(64, 8, kernel_size=(1, 1), stride=(1, 1))
          (1): ReLU(inplace=True)
        )
        (pos_func): PositionEmbeddingCoordsSine(type=fourier, scale=6.283185307179586, normalize=False, gaussB=torch.Size([6, 32]), gaussBsum=1.153261661529541)
      )
    )
    (out_cls): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=19, bias=True)
    )
    (out_score): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=1, bias=True)
    )
    (out_bbox): Sequential(
      (0): Linear(in_features=256, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=3, bias=True)
    )
    (x_mask): Sequential(
      (0): Linear(in_features=32, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=256, bias=True)
    )
  )
  (criterion): Criterion(
    (matcher): HungarianMatcher()
  )
)
2025-08-15 11:47:59,477 - INFO - Parameters: 22.35M
2025-08-15 11:47:59,480 - INFO - Load pretrain from checkpoints/sstnet_pretrain.pth
2025-08-15 11:47:59,576 - WARNING - The model and loaded state dict do not match exactly

size mismatch for input_conv.0.weight: copying a param with shape torch.Size([32, 3, 3, 3, 6]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 9]).
unexpected key in source state_dict: linear.0.weight, linear.0.bias, linear.1.weight, linear.1.bias, linear.1.running_mean, linear.1.running_var, linear.1.num_batches_tracked, linear.3.weight, linear.3.bias, offset.0.weight, offset.0.bias, offset.1.weight, offset.1.bias, offset.1.running_mean, offset.1.running_var, offset.1.num_batches_tracked, offset_linear.weight, offset_linear.bias, superpoint_linear.0.FC.weight, superpoint_linear.0.FC.bias, superpoint_linear.0.norm.weight, superpoint_linear.0.norm.bias, superpoint_linear.0.norm.running_mean, superpoint_linear.0.norm.running_var, superpoint_linear.0.norm.num_batches_tracked, superpoint_linear.1.FC.weight, superpoint_linear.1.FC.bias, superpoint_linear.1.norm.weight, superpoint_linear.1.norm.bias, superpoint_linear.1.norm.running_mean, superpoint_linear.1.norm.running_var, superpoint_linear.1.norm.num_batches_tracked, fusion_linear.0.FC.weight, fusion_linear.0.FC.bias, fusion_linear.0.norm.weight, fusion_linear.0.norm.bias, fusion_linear.0.norm.running_mean, fusion_linear.0.norm.running_var, fusion_linear.0.norm.num_batches_tracked, fusion_linear.1.FC.weight, fusion_linear.1.FC.bias, fusion_linear.1.norm.weight, fusion_linear.1.norm.bias, fusion_linear.1.norm.running_mean, fusion_linear.1.norm.running_var, fusion_linear.1.norm.num_batches_tracked, fusion_linear.2.FC.weight, fusion_linear.2.FC.bias, fusion_linear.2.norm.weight, fusion_linear.2.norm.bias, fusion_linear.2.norm.running_mean, fusion_linear.2.norm.running_var, fusion_linear.2.norm.num_batches_tracked, fusion_linear.3.FC.weight, fusion_linear.3.FC.bias, refine_gcn.gc1.weight, refine_gcn.gc1.bias, refine_gcn.gc2.weight, refine_gcn.gc2.bias, refine_gcn.gc3.weight, refine_gcn.gc3.bias, score_unet.blocks.block0.conv_branch.0.weight, score_unet.blocks.block0.conv_branch.0.bias, score_unet.blocks.block0.conv_branch.0.running_mean, score_unet.blocks.block0.conv_branch.0.running_var, score_unet.blocks.block0.conv_branch.0.num_batches_tracked, score_unet.blocks.block0.conv_branch.2.weight, score_unet.blocks.block0.conv_branch.3.weight, score_unet.blocks.block0.conv_branch.3.bias, score_unet.blocks.block0.conv_branch.3.running_mean, score_unet.blocks.block0.conv_branch.3.running_var, score_unet.blocks.block0.conv_branch.3.num_batches_tracked, score_unet.blocks.block0.conv_branch.5.weight, score_unet.blocks.block1.conv_branch.0.weight, score_unet.blocks.block1.conv_branch.0.bias, score_unet.blocks.block1.conv_branch.0.running_mean, score_unet.blocks.block1.conv_branch.0.running_var, score_unet.blocks.block1.conv_branch.0.num_batches_tracked, score_unet.blocks.block1.conv_branch.2.weight, score_unet.blocks.block1.conv_branch.3.weight, score_unet.blocks.block1.conv_branch.3.bias, score_unet.blocks.block1.conv_branch.3.running_mean, score_unet.blocks.block1.conv_branch.3.running_var, score_unet.blocks.block1.conv_branch.3.num_batches_tracked, score_unet.blocks.block1.conv_branch.5.weight, score_unet.conv.0.weight, score_unet.conv.0.bias, score_unet.conv.0.running_mean, score_unet.conv.0.running_var, score_unet.conv.0.num_batches_tracked, score_unet.conv.2.weight, score_unet.u.blocks.block0.conv_branch.0.weight, score_unet.u.blocks.block0.conv_branch.0.bias, score_unet.u.blocks.block0.conv_branch.0.running_mean, score_unet.u.blocks.block0.conv_branch.0.running_var, score_unet.u.blocks.block0.conv_branch.0.num_batches_tracked, score_unet.u.blocks.block0.conv_branch.2.weight, score_unet.u.blocks.block0.conv_branch.3.weight, score_unet.u.blocks.block0.conv_branch.3.bias, score_unet.u.blocks.block0.conv_branch.3.running_mean, score_unet.u.blocks.block0.conv_branch.3.running_var, score_unet.u.blocks.block0.conv_branch.3.num_batches_tracked, score_unet.u.blocks.block0.conv_branch.5.weight, score_unet.u.blocks.block1.conv_branch.0.weight, score_unet.u.blocks.block1.conv_branch.0.bias, score_unet.u.blocks.block1.conv_branch.0.running_mean, score_unet.u.blocks.block1.conv_branch.0.running_var, score_unet.u.blocks.block1.conv_branch.0.num_batches_tracked, score_unet.u.blocks.block1.conv_branch.2.weight, score_unet.u.blocks.block1.conv_branch.3.weight, score_unet.u.blocks.block1.conv_branch.3.bias, score_unet.u.blocks.block1.conv_branch.3.running_mean, score_unet.u.blocks.block1.conv_branch.3.running_var, score_unet.u.blocks.block1.conv_branch.3.num_batches_tracked, score_unet.u.blocks.block1.conv_branch.5.weight, score_unet.deconv.0.weight, score_unet.deconv.0.bias, score_unet.deconv.0.running_mean, score_unet.deconv.0.running_var, score_unet.deconv.0.num_batches_tracked, score_unet.deconv.2.weight, score_unet.blocks_tail.block0.i_branch.0.weight, score_unet.blocks_tail.block0.conv_branch.0.weight, score_unet.blocks_tail.block0.conv_branch.0.bias, score_unet.blocks_tail.block0.conv_branch.0.running_mean, score_unet.blocks_tail.block0.conv_branch.0.running_var, score_unet.blocks_tail.block0.conv_branch.0.num_batches_tracked, score_unet.blocks_tail.block0.conv_branch.2.weight, score_unet.blocks_tail.block0.conv_branch.3.weight, score_unet.blocks_tail.block0.conv_branch.3.bias, score_unet.blocks_tail.block0.conv_branch.3.running_mean, score_unet.blocks_tail.block0.conv_branch.3.running_var, score_unet.blocks_tail.block0.conv_branch.3.num_batches_tracked, score_unet.blocks_tail.block0.conv_branch.5.weight, score_unet.blocks_tail.block1.conv_branch.0.weight, score_unet.blocks_tail.block1.conv_branch.0.bias, score_unet.blocks_tail.block1.conv_branch.0.running_mean, score_unet.blocks_tail.block1.conv_branch.0.running_var, score_unet.blocks_tail.block1.conv_branch.0.num_batches_tracked, score_unet.blocks_tail.block1.conv_branch.2.weight, score_unet.blocks_tail.block1.conv_branch.3.weight, score_unet.blocks_tail.block1.conv_branch.3.bias, score_unet.blocks_tail.block1.conv_branch.3.running_mean, score_unet.blocks_tail.block1.conv_branch.3.running_var, score_unet.blocks_tail.block1.conv_branch.3.num_batches_tracked, score_unet.blocks_tail.block1.conv_branch.5.weight, score_outputlayer.0.weight, score_outputlayer.0.bias, score_outputlayer.0.running_mean, score_outputlayer.0.running_var, score_outputlayer.0.num_batches_tracked, score_linear.weight, score_linear.bias

missing keys in source state_dict: mlp.0.weight, mlp.0.bias, mlp.2.weight, mlp.2.bias, pooling_linear.0.weight, pooling_linear.0.bias, pooling_linear.1.weight, pooling_linear.1.bias, pooling_linear.1.running_mean, pooling_linear.1.running_var, pooling_linear.3.weight, pooling_linear.3.bias, pooling_linear.4.weight, pooling_linear.4.bias, pooling_linear.4.running_mean, pooling_linear.4.running_var, pooling_linear.6.weight, pooling_linear.6.bias, pooling_linear1.0.weight, pooling_linear1.0.bias, pooling_linear1.1.weight, pooling_linear1.1.bias, pooling_linear1.1.running_mean, pooling_linear1.1.running_var, pooling_linear1.3.weight, pooling_linear1.3.bias, pooling_linear1.4.weight, pooling_linear1.4.bias, pooling_linear1.4.running_mean, pooling_linear1.4.running_var, pooling_linear1.6.weight, pooling_linear1.6.bias, coords_linear.0.weight, coords_linear.0.bias, coords_linear.1.weight, coords_linear.1.bias, coords_linear.1.running_mean, coords_linear.1.running_var, coords_linear.3.weight, coords_linear.3.bias, coords_linear.4.weight, coords_linear.4.bias, coords_linear.4.running_mean, coords_linear.4.running_var, coords_linear.6.weight, coords_linear.6.bias, decoder.input_proj.0.weight, decoder.input_proj.0.bias, decoder.input_proj.1.weight, decoder.input_proj.1.bias, decoder.refpoint_embed.weight, decoder.key_position_embedding.gauss_B, decoder.decoder.layers.0.relative_pos_query_table, decoder.decoder.layers.0.relative_pos_key_table, decoder.decoder.layers.0.relative_pos_value_table, decoder.decoder.layers.0.sa_qcontent_proj.weight, decoder.decoder.layers.0.sa_qcontent_proj.bias, decoder.decoder.layers.0.sa_qpos_proj.weight, decoder.decoder.layers.0.sa_qpos_proj.bias, decoder.decoder.layers.0.sa_kcontent_proj.weight, decoder.decoder.layers.0.sa_kcontent_proj.bias, decoder.decoder.layers.0.sa_kpos_proj.weight, decoder.decoder.layers.0.sa_kpos_proj.bias, decoder.decoder.layers.0.sa_v_proj.weight, decoder.decoder.layers.0.sa_v_proj.bias, decoder.decoder.layers.0.self_attn.out_proj.weight, decoder.decoder.layers.0.self_attn.out_proj.bias, decoder.decoder.layers.0.ca_qcontent_proj.weight, decoder.decoder.layers.0.ca_qcontent_proj.bias, decoder.decoder.layers.0.ca_qpos_proj.weight, decoder.decoder.layers.0.ca_qpos_proj.bias, decoder.decoder.layers.0.ca_kcontent_proj.weight, decoder.decoder.layers.0.ca_kcontent_proj.bias, decoder.decoder.layers.0.ca_kpos_proj.weight, decoder.decoder.layers.0.ca_kpos_proj.bias, decoder.decoder.layers.0.ca_v_proj.weight, decoder.decoder.layers.0.ca_v_proj.bias, decoder.decoder.layers.0.ca_qpos_sine_proj.weight, decoder.decoder.layers.0.ca_qpos_sine_proj.bias, decoder.decoder.layers.0.cross_attn.out_proj.weight, decoder.decoder.layers.0.cross_attn.out_proj.bias, decoder.decoder.layers.0.linear1.weight, decoder.decoder.layers.0.linear1.bias, decoder.decoder.layers.0.linear2.weight, decoder.decoder.layers.0.linear2.bias, decoder.decoder.layers.0.norm1.weight, decoder.decoder.layers.0.norm1.bias, decoder.decoder.layers.0.norm2.weight, decoder.decoder.layers.0.norm2.bias, decoder.decoder.layers.0.norm3.weight, decoder.decoder.layers.0.norm3.bias, decoder.decoder.layers.1.relative_pos_query_table, decoder.decoder.layers.1.relative_pos_key_table, decoder.decoder.layers.1.relative_pos_value_table, decoder.decoder.layers.1.sa_qcontent_proj.weight, decoder.decoder.layers.1.sa_qcontent_proj.bias, decoder.decoder.layers.1.sa_qpos_proj.weight, decoder.decoder.layers.1.sa_qpos_proj.bias, decoder.decoder.layers.1.sa_kcontent_proj.weight, decoder.decoder.layers.1.sa_kcontent_proj.bias, decoder.decoder.layers.1.sa_kpos_proj.weight, decoder.decoder.layers.1.sa_kpos_proj.bias, decoder.decoder.layers.1.sa_v_proj.weight, decoder.decoder.layers.1.sa_v_proj.bias, decoder.decoder.layers.1.self_attn.out_proj.weight, decoder.decoder.layers.1.self_attn.out_proj.bias, decoder.decoder.layers.1.ca_qcontent_proj.weight, decoder.decoder.layers.1.ca_qcontent_proj.bias, decoder.decoder.layers.1.ca_kcontent_proj.weight, decoder.decoder.layers.1.ca_kcontent_proj.bias, decoder.decoder.layers.1.ca_kpos_proj.weight, decoder.decoder.layers.1.ca_kpos_proj.bias, decoder.decoder.layers.1.ca_v_proj.weight, decoder.decoder.layers.1.ca_v_proj.bias, decoder.decoder.layers.1.ca_qpos_sine_proj.weight, decoder.decoder.layers.1.ca_qpos_sine_proj.bias, decoder.decoder.layers.1.cross_attn.out_proj.weight, decoder.decoder.layers.1.cross_attn.out_proj.bias, decoder.decoder.layers.1.linear1.weight, decoder.decoder.layers.1.linear1.bias, decoder.decoder.layers.1.linear2.weight, decoder.decoder.layers.1.linear2.bias, decoder.decoder.layers.1.norm1.weight, decoder.decoder.layers.1.norm1.bias, decoder.decoder.layers.1.norm2.weight, decoder.decoder.layers.1.norm2.bias, decoder.decoder.layers.1.norm3.weight, decoder.decoder.layers.1.norm3.bias, decoder.decoder.layers.2.relative_pos_query_table, decoder.decoder.layers.2.relative_pos_key_table, decoder.decoder.layers.2.relative_pos_value_table, decoder.decoder.layers.2.sa_qcontent_proj.weight, decoder.decoder.layers.2.sa_qcontent_proj.bias, decoder.decoder.layers.2.sa_qpos_proj.weight, decoder.decoder.layers.2.sa_qpos_proj.bias, decoder.decoder.layers.2.sa_kcontent_proj.weight, decoder.decoder.layers.2.sa_kcontent_proj.bias, decoder.decoder.layers.2.sa_kpos_proj.weight, decoder.decoder.layers.2.sa_kpos_proj.bias, decoder.decoder.layers.2.sa_v_proj.weight, decoder.decoder.layers.2.sa_v_proj.bias, decoder.decoder.layers.2.self_attn.out_proj.weight, decoder.decoder.layers.2.self_attn.out_proj.bias, decoder.decoder.layers.2.ca_qcontent_proj.weight, decoder.decoder.layers.2.ca_qcontent_proj.bias, decoder.decoder.layers.2.ca_kcontent_proj.weight, decoder.decoder.layers.2.ca_kcontent_proj.bias, decoder.decoder.layers.2.ca_kpos_proj.weight, decoder.decoder.layers.2.ca_kpos_proj.bias, decoder.decoder.layers.2.ca_v_proj.weight, decoder.decoder.layers.2.ca_v_proj.bias, decoder.decoder.layers.2.ca_qpos_sine_proj.weight, decoder.decoder.layers.2.ca_qpos_sine_proj.bias, decoder.decoder.layers.2.cross_attn.out_proj.weight, decoder.decoder.layers.2.cross_attn.out_proj.bias, decoder.decoder.layers.2.linear1.weight, decoder.decoder.layers.2.linear1.bias, decoder.decoder.layers.2.linear2.weight, decoder.decoder.layers.2.linear2.bias, decoder.decoder.layers.2.norm1.weight, decoder.decoder.layers.2.norm1.bias, decoder.decoder.layers.2.norm2.weight, decoder.decoder.layers.2.norm2.bias, decoder.decoder.layers.2.norm3.weight, decoder.decoder.layers.2.norm3.bias, decoder.decoder.layers.3.relative_pos_query_table, decoder.decoder.layers.3.relative_pos_key_table, decoder.decoder.layers.3.relative_pos_value_table, decoder.decoder.layers.3.sa_qcontent_proj.weight, decoder.decoder.layers.3.sa_qcontent_proj.bias, decoder.decoder.layers.3.sa_qpos_proj.weight, decoder.decoder.layers.3.sa_qpos_proj.bias, decoder.decoder.layers.3.sa_kcontent_proj.weight, decoder.decoder.layers.3.sa_kcontent_proj.bias, decoder.decoder.layers.3.sa_kpos_proj.weight, decoder.decoder.layers.3.sa_kpos_proj.bias, decoder.decoder.layers.3.sa_v_proj.weight, decoder.decoder.layers.3.sa_v_proj.bias, decoder.decoder.layers.3.self_attn.out_proj.weight, decoder.decoder.layers.3.self_attn.out_proj.bias, decoder.decoder.layers.3.ca_qcontent_proj.weight, decoder.decoder.layers.3.ca_qcontent_proj.bias, decoder.decoder.layers.3.ca_kcontent_proj.weight, decoder.decoder.layers.3.ca_kcontent_proj.bias, decoder.decoder.layers.3.ca_kpos_proj.weight, decoder.decoder.layers.3.ca_kpos_proj.bias, decoder.decoder.layers.3.ca_v_proj.weight, decoder.decoder.layers.3.ca_v_proj.bias, decoder.decoder.layers.3.ca_qpos_sine_proj.weight, decoder.decoder.layers.3.ca_qpos_sine_proj.bias, decoder.decoder.layers.3.cross_attn.out_proj.weight, decoder.decoder.layers.3.cross_attn.out_proj.bias, decoder.decoder.layers.3.linear1.weight, decoder.decoder.layers.3.linear1.bias, decoder.decoder.layers.3.linear2.weight, decoder.decoder.layers.3.linear2.bias, decoder.decoder.layers.3.norm1.weight, decoder.decoder.layers.3.norm1.bias, decoder.decoder.layers.3.norm2.weight, decoder.decoder.layers.3.norm2.bias, decoder.decoder.layers.3.norm3.weight, decoder.decoder.layers.3.norm3.bias, decoder.decoder.layers.4.relative_pos_query_table, decoder.decoder.layers.4.relative_pos_key_table, decoder.decoder.layers.4.relative_pos_value_table, decoder.decoder.layers.4.sa_qcontent_proj.weight, decoder.decoder.layers.4.sa_qcontent_proj.bias, decoder.decoder.layers.4.sa_qpos_proj.weight, decoder.decoder.layers.4.sa_qpos_proj.bias, decoder.decoder.layers.4.sa_kcontent_proj.weight, decoder.decoder.layers.4.sa_kcontent_proj.bias, decoder.decoder.layers.4.sa_kpos_proj.weight, decoder.decoder.layers.4.sa_kpos_proj.bias, decoder.decoder.layers.4.sa_v_proj.weight, decoder.decoder.layers.4.sa_v_proj.bias, decoder.decoder.layers.4.self_attn.out_proj.weight, decoder.decoder.layers.4.self_attn.out_proj.bias, decoder.decoder.layers.4.ca_qcontent_proj.weight, decoder.decoder.layers.4.ca_qcontent_proj.bias, decoder.decoder.layers.4.ca_kcontent_proj.weight, decoder.decoder.layers.4.ca_kcontent_proj.bias, decoder.decoder.layers.4.ca_kpos_proj.weight, decoder.decoder.layers.4.ca_kpos_proj.bias, decoder.decoder.layers.4.ca_v_proj.weight, decoder.decoder.layers.4.ca_v_proj.bias, decoder.decoder.layers.4.ca_qpos_sine_proj.weight, decoder.decoder.layers.4.ca_qpos_sine_proj.bias, decoder.decoder.layers.4.cross_attn.out_proj.weight, decoder.decoder.layers.4.cross_attn.out_proj.bias, decoder.decoder.layers.4.linear1.weight, decoder.decoder.layers.4.linear1.bias, decoder.decoder.layers.4.linear2.weight, decoder.decoder.layers.4.linear2.bias, decoder.decoder.layers.4.norm1.weight, decoder.decoder.layers.4.norm1.bias, decoder.decoder.layers.4.norm2.weight, decoder.decoder.layers.4.norm2.bias, decoder.decoder.layers.4.norm3.weight, decoder.decoder.layers.4.norm3.bias, decoder.decoder.layers.5.relative_pos_query_table, decoder.decoder.layers.5.relative_pos_key_table, decoder.decoder.layers.5.relative_pos_value_table, decoder.decoder.layers.5.sa_qcontent_proj.weight, decoder.decoder.layers.5.sa_qcontent_proj.bias, decoder.decoder.layers.5.sa_qpos_proj.weight, decoder.decoder.layers.5.sa_qpos_proj.bias, decoder.decoder.layers.5.sa_kcontent_proj.weight, decoder.decoder.layers.5.sa_kcontent_proj.bias, decoder.decoder.layers.5.sa_kpos_proj.weight, decoder.decoder.layers.5.sa_kpos_proj.bias, decoder.decoder.layers.5.sa_v_proj.weight, decoder.decoder.layers.5.sa_v_proj.bias, decoder.decoder.layers.5.self_attn.out_proj.weight, decoder.decoder.layers.5.self_attn.out_proj.bias, decoder.decoder.layers.5.ca_qcontent_proj.weight, decoder.decoder.layers.5.ca_qcontent_proj.bias, decoder.decoder.layers.5.ca_kcontent_proj.weight, decoder.decoder.layers.5.ca_kcontent_proj.bias, decoder.decoder.layers.5.ca_kpos_proj.weight, decoder.decoder.layers.5.ca_kpos_proj.bias, decoder.decoder.layers.5.ca_v_proj.weight, decoder.decoder.layers.5.ca_v_proj.bias, decoder.decoder.layers.5.ca_qpos_sine_proj.weight, decoder.decoder.layers.5.ca_qpos_sine_proj.bias, decoder.decoder.layers.5.cross_attn.out_proj.weight, decoder.decoder.layers.5.cross_attn.out_proj.bias, decoder.decoder.layers.5.linear1.weight, decoder.decoder.layers.5.linear1.bias, decoder.decoder.layers.5.linear2.weight, decoder.decoder.layers.5.linear2.bias, decoder.decoder.layers.5.norm1.weight, decoder.decoder.layers.5.norm1.bias, decoder.decoder.layers.5.norm2.weight, decoder.decoder.layers.5.norm2.bias, decoder.decoder.layers.5.norm3.weight, decoder.decoder.layers.5.norm3.bias, decoder.decoder.layers_cross.0.relative_pos_query_table, decoder.decoder.layers_cross.0.relative_pos_key_table, decoder.decoder.layers_cross.0.relative_pos_value_table, decoder.decoder.layers_cross.0.ca_qcontent_proj.weight, decoder.decoder.layers_cross.0.ca_qcontent_proj.bias, decoder.decoder.layers_cross.0.ca_qpos_proj.weight, decoder.decoder.layers_cross.0.ca_qpos_proj.bias, decoder.decoder.layers_cross.0.ca_kcontent_proj.weight, decoder.decoder.layers_cross.0.ca_kcontent_proj.bias, decoder.decoder.layers_cross.0.ca_kpos_proj.weight, decoder.decoder.layers_cross.0.ca_kpos_proj.bias, decoder.decoder.layers_cross.0.ca_v_proj.weight, decoder.decoder.layers_cross.0.ca_v_proj.bias, decoder.decoder.layers_cross.0.ca_qpos_sine_proj.weight, decoder.decoder.layers_cross.0.ca_qpos_sine_proj.bias, decoder.decoder.layers_cross.0.cross_attn.out_proj.weight, decoder.decoder.layers_cross.0.cross_attn.out_proj.bias, decoder.decoder.layers_cross.0.linear1.weight, decoder.decoder.layers_cross.0.linear1.bias, decoder.decoder.layers_cross.0.linear2.weight, decoder.decoder.layers_cross.0.linear2.bias, decoder.decoder.layers_cross.0.norm1.weight, decoder.decoder.layers_cross.0.norm1.bias, decoder.decoder.layers_cross.0.norm2.weight, decoder.decoder.layers_cross.0.norm2.bias, decoder.decoder.layers_cross.0.norm3.weight, decoder.decoder.layers_cross.0.norm3.bias, decoder.decoder.layers_cross.1.relative_pos_query_table, decoder.decoder.layers_cross.1.relative_pos_key_table, decoder.decoder.layers_cross.1.relative_pos_value_table, decoder.decoder.layers_cross.1.ca_qcontent_proj.weight, decoder.decoder.layers_cross.1.ca_qcontent_proj.bias, decoder.decoder.layers_cross.1.ca_qpos_proj.weight, decoder.decoder.layers_cross.1.ca_qpos_proj.bias, decoder.decoder.layers_cross.1.ca_kcontent_proj.weight, decoder.decoder.layers_cross.1.ca_kcontent_proj.bias, decoder.decoder.layers_cross.1.ca_kpos_proj.weight, decoder.decoder.layers_cross.1.ca_kpos_proj.bias, decoder.decoder.layers_cross.1.ca_v_proj.weight, decoder.decoder.layers_cross.1.ca_v_proj.bias, decoder.decoder.layers_cross.1.ca_qpos_sine_proj.weight, decoder.decoder.layers_cross.1.ca_qpos_sine_proj.bias, decoder.decoder.layers_cross.1.cross_attn.out_proj.weight, decoder.decoder.layers_cross.1.cross_attn.out_proj.bias, decoder.decoder.layers_cross.1.linear1.weight, decoder.decoder.layers_cross.1.linear1.bias, decoder.decoder.layers_cross.1.linear2.weight, decoder.decoder.layers_cross.1.linear2.bias, decoder.decoder.layers_cross.1.norm1.weight, decoder.decoder.layers_cross.1.norm1.bias, decoder.decoder.layers_cross.1.norm2.weight, decoder.decoder.layers_cross.1.norm2.bias, decoder.decoder.layers_cross.1.norm3.weight, decoder.decoder.layers_cross.1.norm3.bias, decoder.decoder.norm.weight, decoder.decoder.norm.bias, decoder.decoder.position_embedding.gauss_B, decoder.decoder.ref_point_head.layers.0.weight, decoder.decoder.ref_point_head.layers.0.bias, decoder.decoder.ref_point_head.layers.1.weight, decoder.decoder.ref_point_head.layers.1.bias, decoder.decoder.bbox_embed.layers.0.weight, decoder.decoder.bbox_embed.layers.0.bias, decoder.decoder.bbox_embed.layers.1.weight, decoder.decoder.bbox_embed.layers.1.bias, decoder.decoder.bbox_embed.layers.2.weight, decoder.decoder.bbox_embed.layers.2.bias, decoder.decoder.position_relation_embedding.pos_proj.0.weight, decoder.decoder.position_relation_embedding.pos_proj.0.bias, decoder.decoder.position_relation_embedding.pos_func.gauss_B, decoder.out_cls.0.weight, decoder.out_cls.0.bias, decoder.out_cls.2.weight, decoder.out_cls.2.bias, decoder.out_score.0.weight, decoder.out_score.0.bias, decoder.out_score.2.weight, decoder.out_score.2.bias, decoder.out_bbox.0.weight, decoder.out_bbox.0.bias, decoder.out_bbox.2.weight, decoder.out_bbox.2.bias, decoder.x_mask.0.weight, decoder.x_mask.0.bias, decoder.x_mask.2.weight, decoder.x_mask.2.bias, criterion.class_weight, criterion.loss_weight, criterion.matcher.cost_weight

2025-08-15 11:47:59,588 - INFO - Load train dataset: 1201 scans
2025-08-15 11:47:59,591 - INFO - Load val dataset: 312 scans
2025-08-15 11:47:59,591 - INFO - Training
Traceback (most recent call last):
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/tools/train.py", line 210, in <module>
    main()
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/tools/train.py", line 194, in main
    train(epoch, model, train_loader, optimizer, lr_scheduler, cfg, logger, writer)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/tools/train.py", line 51, in train
    loss, log_vars = model(batch, mode='loss')
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/relation3d.py", line 96, in forward
    return self.loss(**batch)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/utils/utils.py", line 20, in wrapper
    return func(*new_args, **new_kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/relation3d.py", line 108, in loss
    out, sp_feats_update_list, _ = self.decoder(sp_feats, sp_coords1, batch_offsets, self.epoch)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/query_decoder.py", line 295, in forward
    return self.forward_iter_pred(x, pos, batch_offsets, epoch)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/query_decoder.py", line 243, in forward_iter_pred
    intermediate_results, ref_points, mask_feats_batched, self_attn = self.decoder(tgt=query.new_zeros(num_queries, B, d_model),
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/transformer.py", line 134, in forward
    output, attn1 = layer(output, memory, query_coords_float=reference_points_coords_float, key_coords_float=coords_float, tgt_mask=tgt_mask,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/transformer.py", line 376, in forward
    return self.forward_post(tgt, memory, query_coords_float, key_coords_float, tgt_mask, memory_mask,
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/transformer.py", line 324, in forward_post
    tgt2 = self.cross_attn(query=q,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/attention_rpe.py", line 164, in forward
    return multi_head_attention_forward(
  File "/home/qinyuan_fan/woc_tub_fan_v4/workspace/woc/relation3d/model/attention_rpe.py", line 374, in multi_head_attention_forward
    attn_pos_bias = torch.zeros_like(attn_output_weights) #[bsz * num_heads, tgt_len, src_len]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.38 GiB. GPU 0 has a total capacty of 47.51 GiB of which 2.46 GiB is free. Process 1137064 has 45.03 GiB memory in use. Of the allocated memory 44.08 GiB is allocated by PyTorch, and 469.43 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Fan-QY** [comment]
The problem has been solved. I guess it was because I was using the most refined method of generating superpoints in “Superpoint Transformer”. I didn't use “Segemantator”.
